package io.github.mylyed.messenger.persist.entity;

import java.io.Serializable;
import java.util.Date;

public class Friend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.user_id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friend_id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    private Integer friendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friend_group_id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    private Integer friendGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.create_time
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.update_time
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friend
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.id
     *
     * @return the value of friend.id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.id
     *
     * @param id the value for friend.id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.user_id
     *
     * @return the value of friend.user_id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.user_id
     *
     * @param userId the value for friend.user_id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friend_id
     *
     * @return the value of friend.friend_id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friend_id
     *
     * @param friendId the value for friend.friend_id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friend_group_id
     *
     * @return the value of friend.friend_group_id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public Integer getFriendGroupId() {
        return friendGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friend_group_id
     *
     * @param friendGroupId the value for friend.friend_group_id
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public void setFriendGroupId(Integer friendGroupId) {
        this.friendGroupId = friendGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.create_time
     *
     * @return the value of friend.create_time
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.create_time
     *
     * @param createTime the value for friend.create_time
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.update_time
     *
     * @return the value of friend.update_time
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.update_time
     *
     * @param updateTime the value for friend.update_time
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}