package io.github.mylyed.messenger.persist.mapper;

import io.github.mylyed.messenger.persist.entity.FriendGroup;
import io.github.mylyed.messenger.persist.entity.FriendGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    long countByExample(FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    int deleteByExample(FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    int insert(FriendGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    int insertSelective(FriendGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    List<FriendGroup> selectByExample(FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    FriendGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") FriendGroup record, @Param("example") FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    int updateByExample(@Param("record") FriendGroup record, @Param("example") FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    int updateByPrimaryKeySelective(FriendGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated Wed Jul 17 17:31:59 CST 2019
     */
    int updateByPrimaryKey(FriendGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FriendGroup selectOneByExample(FriendGroupExample example);
}